#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6.\*

sed -i "/errorfile 504 /etc/haproxy/errors/504.http/a backend mybackend\n  balance roundrobin\n  mode http\
  \n  server web-01 3.236.88.113:80 check\n  server web-02 54.237.80.103:80 check\n\nfrontend myfrontend\
  \n  bind *:80\nmode http\ndefault_backend mybackend" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
