#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
sudo pkill apache2
sudo chmod 755 /etc/nginx/nginx.conf
sudo service nginx restart
